import { Link } from "react-router-dom";
import BlogPost from "@/components/BlogPost";

const SelfDirectedIraRealEstate = () => (
  <BlogPost
    title="How to Buy Real Estate With a Self-Directed IRA"
    metaDesc="A self-directed IRA lets you hold rental property inside a retirement account — tax-deferred or tax-free with a Roth. Here's how it works, the strict rules you must follow, and where investors get into serious trouble."
    slug="financing/self-directed-ira-real-estate"
    datePublished="2026-02-13"
    category="Financing"
    faqs={[
      { q: "What is a self-directed IRA?", a: "A self-directed IRA (SDIRA) is a retirement account that allows you to invest in alternative assets — including real estate, private loans, precious metals, and more — beyond the stocks and bonds offered by conventional brokerages. You maintain control over investment decisions, but the account requires a custodian that specializes in alternative assets, such as Equity Trust, Advanta IRA, or uDirect IRA. Fidelity, Schwab, and Vanguard do not offer self-directed IRAs." },
      { q: "What is a prohibited transaction in a self-directed IRA?", a: "A prohibited transaction is any transaction between your IRA and a disqualified person — which includes you, your spouse, your parents, your children, and entities where you have a 50% or greater ownership interest. You cannot sell property to your IRA, buy property from your IRA for personal use, personally perform labor on IRA-owned property, or use IRA funds to benefit yourself or disqualified persons. A single prohibited transaction can disqualify the entire IRA, triggering taxes and penalties on the full account value." },
      { q: "Can a self-directed IRA take out a mortgage?", a: "Yes, but only a non-recourse loan — meaning the lender's only remedy in default is the property itself, not your other IRA assets or personal assets. Non-recourse loans for SDIRAs require larger down payments (typically 30–40%) and carry higher rates than conventional mortgages. Any income generated by the financed portion of the property may be subject to Unrelated Debt-Financed Income (UDFI) tax, which applies even inside a tax-advantaged account and requires a CPA familiar with SDIRA mechanics." },
      { q: "What is the tax advantage of buying real estate in a Roth SDIRA?", a: "In a Roth SDIRA, contributions are made with after-tax money, but qualified withdrawals — including all rental income and appreciation earned by properties held in the account — are completely tax-free. If you buy a rental property in a Roth SDIRA, collect rent for 15 years, and sell it at a significant gain, you owe nothing to the IRS on any of that income or appreciation, provided you meet the qualified distribution rules (account open 5+ years, age 59½ or older)." },
      { q: "Can the self-directed IRA owner manage the property themselves?", a: "You can make investment decisions — choose tenants, set rent, decide to sell — but you cannot personally provide services to the property. That means no self-performed repairs, maintenance, landscaping, or management. The IRA must hire third parties for all of these, and the IRA pays them directly. Performing work yourself is considered a prohibited transaction, and a single violation can expose the entire IRA to disqualification. Hire a professional property manager." },
    ]}
  >
    <p>
      Most investors think of their IRA as a stock account. They park their 401(k) rollover in index funds, let it grow, and pull from it at retirement. The IRS never said it had to work that way. The rules allow retirement funds to be invested in real estate — the same rental property, the same cash flow, the same appreciation — with the tax treatment of a retirement account layered on top.
    </p>

    <p>
      In a Traditional SDIRA, rental income and gains grow tax-deferred. In a Roth SDIRA, they grow completely tax-free. The structure is legitimate, it's been used for decades, and it's underutilized because most financial advisors don't work with alternative assets and most real estate investors don't think to ask about their IRAs.
    </p>

    <h2>How the Mechanics Work</h2>

    <p>
      The fundamental rule: your IRA buys the property — not you. The title goes in the name of the account: "Equity Trust Company FBO [Your Name] IRA." All funds for the purchase come from the IRA. All income goes back to the IRA.
    </p>

    <ol>
      <li><strong>Open a self-directed IRA</strong> with a custodian that handles alternative assets. Companies like Equity Trust, Advanta IRA, and uDirect IRA specialize in this. Standard brokerages don't offer it.</li>
      <li><strong>Fund the account</strong> via a rollover from an existing 401(k) or IRA, a transfer from another custodian, or annual contributions subject to IRS limits.</li>
      <li><strong>Find the property.</strong> You make the investment decision — that's your role as account holder.</li>
      <li><strong>Your IRA purchases the property.</strong> Offer, contract, and closing all happen in the IRA's name. The custodian facilitates the transaction.</li>
      <li><strong>All expenses are paid from the IRA.</strong> Taxes, insurance, repairs, management fees — everything. You cannot write a personal check for IRA property expenses and get reimbursed later.</li>
      <li><strong>All income goes into the IRA.</strong> Rent checks, sale proceeds — back into the account, not your personal bank account.</li>
    </ol>

    <p>
      The last two points are where beginners make expensive mistakes. Even a $150 repair paid personally is a prohibited transaction if it benefits the IRA without going through the custodian. The IRS does not have a de minimis exception for this.
    </p>

    <h2>The Rules You Cannot Break</h2>

    <p>
      The prohibited transaction rules are specific and the consequences are severe. A violation doesn't just create a penalty on the transaction — it can disqualify the entire IRA, making the full account value immediately taxable as ordinary income plus a potential 10% early withdrawal penalty if you're under 59½.
    </p>

    <h3>No Self-Dealing</h3>

    <p>
      You cannot personally benefit from the property. No living there, no vacationing there, no using it for any personal purpose. It is a pure investment.
    </p>

    <h3>No Transactions With Disqualified Persons</h3>

    <p>
      You cannot buy from, sell to, or do business with yourself, your spouse, your parents, your children, grandchildren, or their spouses. You also cannot hire your own company to manage or renovate the property. The IRA must transact with unrelated third parties.
    </p>

    <h3>No Sweat Equity</h3>

    <p>
      You cannot personally perform any work on the property — not repairs, not improvements, not painting. All services are hired out. The IRA pays.
    </p>

    <div className="callout">
      <strong>The practical test:</strong> Before doing anything related to an IRA-owned property, ask whether the action benefits you personally or involves a transaction with a family member. If either answer is yes, stop and consult your custodian or an SDIRA attorney before proceeding.
    </div>

    <h2>Traditional SDIRA vs. Roth SDIRA</h2>

    <p>
      <strong>Traditional SDIRA:</strong> Contributions may be tax-deductible. Rental income and gains grow tax-deferred — you pay nothing until withdrawal. In retirement, distributions are taxed as ordinary income. Best for investors in a higher tax bracket now who expect to be in a lower bracket at retirement.
    </p>

    <p>
      <strong>Roth SDIRA:</strong> Contributions are made after-tax. All qualified withdrawals — including all income and appreciation earned inside the account — are completely tax-free. Best for investors with time for compounding and who expect either higher future tax rates or significant long-term property appreciation.
    </p>

    <p>
      The math on a Roth SDIRA with real estate can be compelling. A property purchased for $120,000 that generates $800/month net income for 20 years and sells for $280,000 represents $192,000 in total rent plus $160,000 in appreciation — $352,000 in gains, potentially none of which is taxable in a qualifying Roth.
    </p>

    <h2>Non-Recourse Loans and UDFI Tax</h2>

    <p>
      If your SDIRA can't fully fund a property purchase with cash, it can borrow — but only through a non-recourse loan. Non-recourse means if the IRA defaults, the lender can only seize the property. They cannot come after your other IRA assets or anything outside the account.
    </p>

    <p>
      Non-recourse loans require larger down payments (typically 30–40%) and come at higher rates than conventional mortgages. The wrinkle: any income generated by the debt-financed portion of the property may be subject to Unrelated Debt-Financed Income (UDFI) tax — a tax that applies to the leveraged fraction of income even inside a tax-advantaged account. This requires a CPA familiar with SDIRA mechanics to handle properly.
    </p>

    <h2>Reserves: The Part Most Guides Skip</h2>

    <p>
      The IRA must have enough liquid cash to cover all property expenses — forever, in theory. You cannot supplement the IRA with personal funds when the water heater breaks. If the IRA runs out of money, you have a serious problem that can only be solved by making new contributions (subject to annual limits) or selling the property.
    </p>

    <p>
      Practical minimum: keep 10–15% of the property value in cash reserves inside the IRA alongside the property. For a $120,000 property, that means $12,000–$18,000 in IRA cash, separate from the purchase price. Replenish reserves through ongoing rent deposits before the next expense cycle hits.
    </p>

    <p>
      For investors using <Link to="/blog/financing/private-money-lender">private money lending</Link> as a strategy, a self-directed Roth IRA is one of the most tax-efficient vehicles — the interest income stays in the account and compounds tax-free. The <a href="https://www.irs.gov/retirement-plans/prohibited-transactions" target="_blank" rel="noopener noreferrer">IRS guidance on prohibited transactions</a> is the definitive reference for what you can and cannot do.
    </p>

    <div className="callout">
      A self-directed IRA is genuinely powerful — the combination of real estate returns and retirement account tax treatment is hard to replicate with other investment structures. But the rules are strict and the penalties for violations are severe. Work with a custodian who specializes in this, a CPA who understands UDFI and SDIRA tax mechanics, and a real estate attorney for transactions. The professional costs are a legitimate IRA expense. The cost of getting it wrong is not.
    </div>
  </BlogPost>
);

export default SelfDirectedIraRealEstate;
